# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: pair_matcher
  password: m@tch*d
  host: localhost

development:
  <<: *default
  database: pair_matcher_development

test:
  <<: *default
  database: pair_matcher_test

# As with config/secrets.yml, you never want to store sensitive information in your code
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: pair_matcher_production
  username: pair_matcher
  password: <%= ENV['PAIR_MATCHER_DATABASE_PASSWORD'] %>
